### PR TITLE
Spotgrid

### PR DESCRIPTION
**Pull request by julienguy**
New version of psf.spotgrid._xypix , the routine that resamples the spots onto the CCD pixel grid.
It is now much more accurate at the expense of an increase of computation time of 30%.

### CODE REVIEW

**Comment by julienguy** [comment]
fixed a bug if xc or yc < 0

**Comment by weaverba137** [comment]
It looks like you added pylab as a dependency.  I think it is better to explicitly use matplotlib, since that's really what it is.

**Comment by julienguy** [comment]
argh ... thanks, I am fixing this

**Comment by weaverba137** [comment]
In the .travis.yml file, change `OPTIONAL_DEPS=false` to `OPTIONAL_DEPS=true` to install matplotlib during Travis tests.

**Pull request merged**
